const fs = require('fs');

// populates the markdown file, will update the data based on user input
function generateMarkdown(data) {
  return `#${data.title}
  
  ## Description 
  ${data.description}
  
  ## Table of Contents
  - [Installation](#installation)
  - [Usage](#usage)
  - [License](#license)
  - [Contributing](#contributing)
  - [Tests](#tests)
  - [Questions](#questions)
  
  ## Link
  ${data.link}
  
  ## Installation 
  ${data.installation}
  
  ## Usage
  ${data.usage}
  
  ## Tests
  ${data.tests}
  
  ## Credits
  ${data.credits}
  
  ## Questions?
  * Email: <${data.email}>
  * GitHub: <https://github.com/${data.username}>
  
  ## Contribute
  ${data.contribute}
  
  ## License
  This project is protected under the ${data.licenseName}.
  ${renderLicenseSection(data.licenseName)}
  For more info, visit ${renderLicenseLink(data.licenseName)}.
  
  Badge : ${renderLicenseBadge(data.licenseName)}.`;
}

// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(licenseName) { 
  const badges = {
    "MIT License": "![License](https://img.shields.io/badge/License-MIT-yellow.svg)",
      "Boost Software License": "![License](https://img.shields.io/badge/License-Boost%201.0-lightblue.svg)",
      "Unlicense Agreement": "![License](https://img.shields.io/badge/license-Unlicense-blue.svg)",
      "Apache License 2.0": "![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)",
      "N/A": "N/A"
  }; 
  return badges [licenseName] || "N/A";
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(licenseName) { 
  const links = {
    "MIT License": "https://opensource.org/licenses/MIT/",
      "Boost Software License": "https://www.boost.org/LICENSE_1_0.txt",
      "Unlicense Agreement": "http://unlicense.org/",
      "Apache License 2.0": "https://www.apache.org/licenses/LICENSE-2.0",
      "N/A": "N/A"
  };
  return links [licenseName] || "";
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(licenseName) { 
  const sections = {
      "MIT License": "Copyright <YEAR> <COPYRIGHT HOLDER> \n Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
      "Boost Software License": "Boost Software License - Version 1.0 - August 17th, 2003.\n Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying documentation covered by this license (the Software) to use, reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject to the following: \n The copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor.\n THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
      "Unlicense Agreement": "This is free and unencumbered software released into the public domain.\n Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.\n In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain. We make this dedication for the benefit of the public at large and to the detriment of our heirs and successors. We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law. \n THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. \n For more information, please refer to <https://unlicense.org>",
      "Apache License 2.0": "Copyright [yyyy] [name of copyright owner] \n Licensed under the Apache License, Version 2.0 (the License); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.",
      "N/A": "N/A",
    };
  return sections [licenseName] || "";
}

module.exports = generateMarkdown, renderLicenseBadge, renderLicenseLink, renderLicenseSection
